version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk-11.0.1
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - gradlew assemble
test_script:
  - gradlew test
