version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - choco install "sonarscanner-msbuild-net46" -y
  - SonarScanner.MSBuild.exe begin /k:"DabEngine" /d:"sonar.host.url=https://sonarcloud.io" /o:"lememeteam-github" /d:"sonar.login=c0d812ff6a8168ca188e7759c4f8a96c12927366"
  - gradlew assemble
  - SonarScanner.MSBuild.exe end /d:"sonar.login=c0d812ff6a8168ca188e7759c4f8a96c12927366"
test_script:
  - gradlew test
